name = "MeasureTheory"
uuid = "eadaa1a4-d27c-401d-8699-e962e1bbc33b"
authors = ["Chad Scherrer <chad.scherrer@gmail.com> and contributors"]
version = "0.8.1"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
DynamicIterators = "6c76993d-992e-5bf1-9e63-34920a5a5a38"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
InfiniteArrays = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
KeywordCalls = "4d827475-d3e4-43d6-abe3-9688362ede9f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
NestedTuples = "a734d2a7-8d68-409b-9419-626914d4061d"
PositiveFactorizations = "85a6dd25-e78a-55b7-8502-1745935b8125"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"
Tricks = "410a4b4d-49e4-4fbc-ab6d-cb71b17b3775"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
Accessors = "0.1"
ArrayInterface = "2,3"
ConcreteStructs = "0.2"
Distributions = "0.23, 0.24, 0.25"
DistributionsAD = "0.6"
DynamicIterators = "0.4.2"
InfiniteArrays = "0.7, 0.8, 0.9, 0.10"
IntervalSets = "0.5"
IterTools = "1"
KeywordCalls = "0.1, 0.2"
MLStyle = "0.4"
MacroTools = "0.5"
MappedArrays = "0.3, 0.4"
MonteCarloMeasurements = "0.10"
NamedTupleTools = "0.13"
NestedTuples = "0.3"
PositiveFactorizations = "0.2"
RandomNumbers = "1"
SimpleTraits = "0.9"
SpecialFunctions = "0.10, 1"
StaticArrays = "0.12, 1"
StatsFuns = "0.9"
TransformVariables = "0.4"
Tullio = "0.2"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
